export default{
    "login": "MrR3set",
    "id": 31925229,
    "node_id": "MDQ6VXNlcjMxOTI1MjI5",
    "avatar_url": "https://avatars3.githubusercontent.com/u/31925229?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/MrR3set",
    "html_url": "https://github.com/MrR3set",
    "followers_url": "https://api.github.com/users/MrR3set/followers",
    "following_url": "https://api.github.com/users/MrR3set/following{/other_user}",
    "gists_url": "https://api.github.com/users/MrR3set/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/MrR3set/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/MrR3set/subscriptions",
    "organizations_url": "https://api.github.com/users/MrR3set/orgs",
    "repos_url": "https://api.github.com/users/MrR3set/repos",
    "events_url": "https://api.github.com/users/MrR3set/events{/privacy}",
    "received_events_url": "https://api.github.com/users/MrR3set/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Bairon Paz",
    "company": "AG Tech",
    "blog": "https://github.com/MrR3set",
    "location": "Southern California",
    "email": null,
    "hireable": true,
    "bio": "Python is overrated.",
    "public_repos": 37,
    "public_gists": 0,
    "followers": 19,
    "following": 16,
    "created_at": "2017-09-13T12:30:44Z",
    "updated_at": "2020-03-03T07:29:20Z"
    }